//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceMoneyCustomer
    {
        public string AdvanceMoneyCustomerID { get; set; }
        public string MeterBillID { get; set; }
        public Nullable<System.DateTime> ForMonth { get; set; }
        public decimal AdvanceMonthAmount { get; set; }
        public string Remark { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual MeterBill MeterBill { get; set; }
    }
}
