//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillCode7Layer
    {
        public BillCode7Layer()
        {
            this.BillCode7LayerDetail = new HashSet<BillCode7LayerDetail>();
            this.Customers = new HashSet<Customer>();
        }
    
        public string BillCode7LayerID { get; set; }
        public long BillCode7LayerNo { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string BillCodeLayerType { get; set; }
    
        public virtual ICollection<BillCode7LayerDetail> BillCode7LayerDetail { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
