//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ManualMeterUnitCollects = new HashSet<ManualMeterUnitCollect>();
            this.MeterUnitCollects = new HashSet<MeterUnitCollect>();
        }
    
        public string CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerNameInEng { get; set; }
        public string CustomerNameInMM { get; set; }
        public string CustomerAddressInEng { get; set; }
        public string CustomerAddressInMM { get; set; }
        public string NRC { get; set; }
        public string LedgerID { get; set; }
        public int PageNo { get; set; }
        public int LineNo { get; set; }
        public string QuarterID { get; set; }
        public string BillDayGroupCode { get; set; }
        public string TransformerID { get; set; }
        public string MeterID { get; set; }
        public string Post { get; set; }
        public string PhoneNo { get; set; }
        public string BillCode7LayerID { get; set; }
        public string PreviousID { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string SMDNo { get; set; }
    
        public virtual BillCode7Layer BillCode7Layer { get; set; }
        public virtual BillDay BillDay { get; set; }
        public virtual Ledger Ledger { get; set; }
        public virtual Meter Meter { get; set; }
        public virtual Quarter Quarter { get; set; }
        public virtual Transformer Transformer { get; set; }
        public virtual ICollection<ManualMeterUnitCollect> ManualMeterUnitCollects { get; set; }
        public virtual ICollection<MeterUnitCollect> MeterUnitCollects { get; set; }
    }
}
