//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterBox
    {
        public MeterBox()
        {
            this.Meters = new HashSet<Meter>();
        }
    
        public string MeterBoxID { get; set; }
        public string MeterBoxCode { get; set; }
        public string PoleID { get; set; }
        public string Box { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string MeterBoxName { get; set; }
    
        public virtual ICollection<Meter> Meters { get; set; }
        public virtual Pole Pole { get; set; }
    }
}
