//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterUnitCollect
    {
        public MeterUnitCollect()
        {
            this.MeterBills = new HashSet<MeterBill>();
        }
    
        public string MeterUnitCollectID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal TotalMeterUnit { get; set; }
        public int BillMonth { get; set; }
        public string TransformerID { get; set; }
        public string PoleID { get; set; }
        public string MeterID { get; set; }
        public decimal UsedUnitKwh { get; set; }
        public decimal GPSX { get; set; }
        public decimal GPSY { get; set; }
        public int MeterStatus { get; set; }
        public string OMRModelNo { get; set; }
        public string DigitalModelNo { get; set; }
        public string BillCode { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Meter Meter { get; set; }
        public virtual ICollection<MeterBill> MeterBills { get; set; }
        public virtual Pole Pole { get; set; }
        public virtual Transformer Transformer { get; set; }
    }
}
