//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterBill
    {
        public MeterBill()
        {
            this.AdvanceMoneyCustomers = new HashSet<AdvanceMoneyCustomer>();
            this.PunishmentCustomers = new HashSet<PunishmentCustomer>();
        }
    
        public string MeterBillID { get; set; }
        public string MeterBillCode { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime LastBillPaidDate { get; set; }
        public Nullable<decimal> ServicesFees { get; set; }
        public decimal MeterFees { get; set; }
        public Nullable<decimal> StreetLightFees { get; set; }
        public decimal TotalFees { get; set; }
        public decimal UsageUnit { get; set; }
        public decimal CurrentMonthUnit { get; set; }
        public decimal PreviousMonthUnit { get; set; }
        public Nullable<decimal> AdvanceMoney { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public bool isPaid { get; set; }
        public Nullable<System.DateTime> BillPayDate { get; set; }
        public string Remark { get; set; }
        public decimal RecivedAmount { get; set; }
        public Nullable<decimal> HorsePowerFees { get; set; }
        public Nullable<decimal> AdditionalFees1 { get; set; }
        public Nullable<decimal> AdditionalFees2 { get; set; }
        public Nullable<decimal> AdditionalFees3 { get; set; }
        public Nullable<int> MeterBillNo { get; set; }
        public string MeterUnitCollectID { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<AdvanceMoneyCustomer> AdvanceMoneyCustomers { get; set; }
        public virtual ICollection<PunishmentCustomer> PunishmentCustomers { get; set; }
        public virtual MeterUnitCollect MeterUnitCollect { get; set; }
    }
}
