//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunishmentRule
    {
        public PunishmentRule()
        {
            this.PunishmentCustomers = new HashSet<PunishmentCustomer>();
        }
    
        public string PunishmentRuleID { get; set; }
        public string PunishmentCode { get; set; }
        public int ExceedMonth { get; set; }
        public decimal Amount { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<PunishmentCustomer> PunishmentCustomers { get; set; }
    }
}
