//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunishmentCustomer
    {
        public string PunishmentCustomerID { get; set; }
        public System.DateTime ForMonth { get; set; }
        public string PunishmentRuleID { get; set; }
        public string MeterBillID { get; set; }
        public decimal PunishmentAmount { get; set; }
        public string Remark { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual PunishmentRule PunishmentRule { get; set; }
        public virtual MeterBill MeterBill { get; set; }
    }
}
