//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransformerHistory
    {
        public string TransformerID { get; set; }
        public string OldTransformerName { get; set; }
        public string TransformerName { get; set; }
        public string Address { get; set; }
        public bool Status { get; set; }
        public string QuarterID { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> GPSX { get; set; }
        public Nullable<decimal> GPSY { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> RatedOutputPower { get; set; }
        public Nullable<int> VoltageRatio { get; set; }
        public string VectorGroup { get; set; }
        public string TypeofCooling { get; set; }
        public Nullable<int> EfficiencyLoad { get; set; }
        public Nullable<int> ImpendanceVoltage { get; set; }
        public Nullable<int> NoloadLoss { get; set; }
        public Nullable<int> FullLoadLoss { get; set; }
        public string TappingRange { get; set; }
        public string Maker { get; set; }
        public string CountryOfOrgin { get; set; }
        public string Standard { get; set; }
    }
}
