//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPS.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarter
    {
        public string QuarterID { get; set; }
        public string QuarterCode { get; set; }
        public string QuarterNameInEng { get; set; }
        public string QuarterNameInMM { get; set; }
        public string Address { get; set; }
        public string TownshipID { get; set; }
        public bool Active { get; set; }
        public string CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
